title: Just the Docs Test BMX
description: Testing flavoured Jekyll/Just-The-Doc site
theme: just-the-docs

url: https://skiedrowski.github.io/jtd_test/bmx

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/skiedrowski/jtd_test

collections:
  bmx:
    output: true
